config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  devise_for :end_users
  devise_for :admins

  namespace :admins do
    resources :end_users, only: [:index, :show, :edit, :update]
  	resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  get 'end_users/yours' => 'end_users#yours', as: 'end_user_yours'
  get 'end_users/yours/edit' => 'end_users#edit', as: 'end_user_edit'
  get 'end_users/leave' => 'end_users#leave', as: 'end_user_leave'
  patch 'end_users/:id/hide' => 'end_users#hide', as: 'end_user_hide'
  resources :end_users, only: [:update]
  
  resources :items, only: [:index, :show]
  
  delete 'cart_items/item/:id' => 'cart_items#destroy_item', as: 'cart_items_destroy_item'
  delete 'cart_items' => 'cart_items#destroy_cart', as: 'cart_items_destroy_cart'
  resources :cart_items, only: [:index, :create, :update]

  post 'orders/confirm' => 'orders#confirm', as: 'confirm_order'
  get 'orders/complete' => 'orders#complete', as: 'complete_order'
  resources :orders, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre
	attachment :image

	has_many :cart_items, dependent: :destroy
	has_many :order_details , dependent: :destroy

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

	def new
		@item = Item.new
	end

	def index
		if params[:search].present?
			@items = Item.where('name LIKE ?', "%#{params[:search]}%")
		else
			@items = Item.all
		end
	end

	def show
		@item = Item.find(params[:id])		
	end

	def edit
		@item = Item.find(params[:id])
	end

	def create
		@item = Item.new(item_params)
		@item.save
		redirect_to admins_items_path
	end

	def update
		@item = Item.find(params[:id])
		@item.update(item_params)
		redirect_to admins_items_path
	end

	private
	def item_params
  		params.require(:item).permit(:genre_id, :name, :introduction, 
  			:sale_status, :price, :image)
	end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

def index
	@end_user = current_end_user
	@items = Item.all
end

end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admins/items/edit.html.erb
<div class="row">
	<div class="col-xs-4 col-xs-offset-1">
		<h3 class="font-bold admin-title" style="margin-bottom: 30px;">商品 編集画面</h3>
	</div>
</div>

<div class="row">
	<%= form_for @item, url: admins_item_path(@item) do |f| %>
		<div class="row">
			<div class="col-xs-3 col-xs-offset-1">
				<div class="row">
					<%= attachment_image_tag @item, :image, format: 'jpeg', fallback: "mv.jpg", size: "300x300"  %>
				</div>
				<div class="row">
					<%= f.attachment_field :image %>
				</div>
			</div>
			<div class="col-xs-4">
				<div class="row form-item">
					<div class="col-xs-6">
						<%= f.label :商品名 %>
					</div>
					<div class="col-xs-6">
						<%= f.text_field :name %>
					</div>
				</div>
				<div class="row form-item">
					<div class="col-xs-6">
						<%= f.label :商品説明 %>
					</div>
					<div class="col-xs-6">
						<%= f.text_area :introduction %>
					</div>
				</div>
				<div class="row form-item">
					<div class="col-xs-6">
						<%= f.label :ジャンル %>
					</div>
					<div class="col-xs-6">
						<%= f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] } %>
					</div>
				</div>
				<div class="row form-item">
					<div class="col-xs-6">
						<%= f.label :税抜き価格 %>
					</div>
					<div class="col-xs-6">
						<%= f.text_field :price %>
					</div>
				</div>
				<div class="row form-item">
					<div class="col-xs-6">
						<%= f.label :販売ステータス %>
					</div>
					<div class="col-xs-6">
						<%= f.label :販売中 %>
						<%= f.radio_button :sale_status, :true %>
						<%= f.label :販売停止中 %>
						<%= f.radio_button :sale_status, :false %>
					</div>
				</div>
				<div class="col-xs-5"></div>

			</div>
		</div>
		<div class="row">
			<div class="col-xs-4 col-xs-offset-8">
				<%= f.submit('変更を保存', class: 'btn btn-info col-xs-6') %>
			</div>
		</div>
	<% end %>
</div>

app/views/admins/items/index.html.erb
<div class="row">
	<div class="col-xs-4 col-xs-offset-1">
		<h3 class="font-bold admin-title">ジャンル追加・一覧画面</h3>
	</div>
</div>

<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<table class="table">
			<thead class="bgc-sil">
				<tr>
					<th class="font-bold">商品ID</th>
					<th class="font-bold">商品名</th>
					<th class="font-bold">税抜き価格</th>
					<th class="font-bold">ジャンル</th>
					<th class="font-bold">ステータス</th>
				</tr>
			</thead>
			<tbody>
				<% @items.each do |item| %>
					<tr>
						<td class="txt-c ver-m">
							<%= item.id %>
						</td>
						<td class="txt-c ver-m">
							<%= link_to admins_item_path(item.id) do %>
								<%= item.name %>
							<% end %>
						</td>
						<td class="txt-c ver-m">
							<%= item.price %>
						</td>
						<td class="txt-c ver-m">
							<%= item.genre.name %>
						</td>
						<td class="txt-c ver-m">
							<% if item.sale_status == true %>
								<p>販売中</p>
							<% else %>
								<p>販売停止中</p>
							<% end %>
						</td>
						
					</tr>

				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admins/items/new.html.erb
<div class="row">
	<div class="col-xs-4 col-xs-offset-1">
		<h3 class="font-bold admin-title" style="margin-bottom: 30px;">商品 新規登録画面</h3>
	</div>
</div>

<div class="row">
	<%= form_for @item, url: admins_items_path do |f| %>
		<div class="row">
			<div class="col-xs-3 col-xs-offset-1">
				<%= f.attachment_field :image %>
			</div>
			<div class="col-xs-4">
				<div class="row form-item">
					<div class="col-xs-6">
						<%= f.label :商品名 %>
					</div>
					<div class="col-xs-6">
						<%= f.text_field :name %>
					</div>
				</div>
				<div class="row form-item">
					<div class="col-xs-6">
						<%= f.label :商品説明 %>
					</div>
					<div class="col-xs-6">
						<%= f.text_area :introduction %>
					</div>
				</div>
				<div class="row form-item">
					<div class="col-xs-6">
						<%= f.label :ジャンル %>
					</div>
					<div class="col-xs-6">
						<%= f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] } %>
					</div>
				</div>
				<div class="row form-item">
					<div class="col-xs-6">
						<%= f.label :税抜き価格 %>
					</div>
					<div class="col-xs-6">
						<%= f.text_field :price %>
					</div>
				</div>
				<div class="row form-item">
					<div class="col-xs-6">
						<%= f.label :販売ステータス %>
					</div>
					<div class="col-xs-6">
						<%= f.label :販売中 %>
						<%= f.radio_button :sale_status, :true %>
						<%= f.label :販売停止中 %>
						<%= f.radio_button :sale_status, :false %>
					</div>
				</div>
				<div class="col-xs-5"></div>

			</div>
		</div>
		<div class="row">
			<div class="col-xs-offset-8">
				<%= f.submit('新規登録', class: 'btn btn-info col-xs-4') %>
			</div>
		</div>
	<% end %>
</div>

app/views/admins/items/show.html.erb
<div class="row" style="margin-top: 40px;">
	<div class="col-xs-4 col-xs-offset-1">
		<h3 class="font-bold admin-title">商品 詳細画面</h3>
	</div>
</div>

<div class="row" style="margin-top: 60px;">
	<div class="col-xs-4">
		<%= attachment_image_tag @item, :image, format: 'jpeg', fallback: "mv.jpg", size: "300x300" %>
	</div>
	<div class="col-xs-6">

		<div class="row">
			<div class="col-xs-4">
				<h4>商品名</h4>
			</div>
			<div class="col-xs-8">
				<h4><%= @item.name %></h4>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-4">
				<h4>商品説明</h4>
			</div>
			<div class="col-xs-8">
				<h4><%= @item.introduction %></h4>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-4">
				<h4>ジャンル</h4>
			</div>
			<div class="col-xs-8">
				<h4><%= @item.genre.name %></h4>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-4">
				<h4>税込価格 (税抜価格)</h4>
			</div>
			<div class="col-xs-8">
				<h4><%= (@item.price * 1.1).round %> (<%= @item.price %>)</h4>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-4">
				<h4>販売ステータス</h4>
			</div>
			<div class="col-xs-8">
				<% if @item.sale_status == true %>
					<h4>販売中</h4>
				<% else %>
					<h4>販売停止中</h4>
				<% end %>
			</div>
		</div>

	</div>
</div>

<div class="row">
	<div class="col-xs-3 col-xs-offset-7">
		<%= link_to "編集する", edit_admins_item_path(@item), class: "btn btn-primary col-xs-8" %>
	</div>
</div>