config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  devise_for :end_users
  devise_for :admins

  namespace :admins do
    resources :end_users, only: [:index, :show, :edit, :update]
  	resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  get 'end_users/yours' => 'end_users#yours', as: 'end_user_yours'
  get 'end_users/yours/edit' => 'end_users#edit', as: 'end_user_edit'
  get 'end_users/leave' => 'end_users#leave', as: 'end_user_leave'
  patch 'end_users/:id/hide' => 'end_users#hide', as: 'end_user_hide'
  resources :end_users, only: [:update]
  
  resources :items, only: [:index, :show]
  
  delete 'cart_items/item/:id' => 'cart_items#destroy_item', as: 'cart_items_destroy_item'
  delete 'cart_items' => 'cart_items#destroy_cart', as: 'cart_items_destroy_cart'
  resources :cart_items, only: [:index, :create, :update]

  post 'orders/confirm' => 'orders#confirm', as: 'confirm_order'
  get 'orders/complete' => 'orders#complete', as: 'complete_order'
  resources :orders, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

	belongs_to :end_user
	belongs_to :item

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart_items = CartItem.all
    @total_price = 0
    @cart_items.each do |cart_item|
      @total_price = @total_price + ((cart_item.item.price*1.1).round)*cart_item.amount 
    end
  end

  def create
    @cart_item = current_end_user.cart_items.new(cart_item_params)
    if presence = current_end_user.cart_items.find_by(item_id: params[:cart_item][:item_id]) 
      amount = @cart_item.amount + presence.amount
      presence.update(amount: amount)
      redirect_to cart_items_path
    else
      @cart_item.save
      redirect_to cart_items_path
    end
  end

  def update
  	@cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy_item
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_cart
    @end_user = current_end_user
    EndUser.find(@end_user.id).cart_items.destroy_all
    redirect_to items_path
  end

  private
  def cart_item_params
  	params.require(:cart_item).permit(:amount, :end_user_id, :item_id)
  end
end

app/views/cart_items/index.html.erb
<div class="row">
	<div class="col-xs-4 col-xs-offset-1">
		<h3 class="font-bold admin-title">ショッピングカート</h3>
	</div>
	<div class="col-xs-3 col-xs-offset-4">
		<%= link_to "カートを空にする", cart_items_destroy_cart_path, method: :delete, data: {confirm: "本当に消しますか?"}, class: "btn btn-danger" %>
	</div>
</div>

<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<div class="row">
			<table class="table table-bordered">
				<thead class="bgc-sil">
					<tr>
						<th><h4 class="font-bold">商品名</h4></th>
						<th><h4 class="font-bold">単価(税込)</h4></th>
						<th><h4 class="font-bold">数量</h4></th>
						<th><h4 class="font-bold">小計</h4></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @cart_items.each do |cart_item| %>
						<tr>
							<td class="txt-c ver-m">
								<%= attachment_image_tag cart_item.item, :image, format: 'jpeg', fallback: "mv.jpg", size: "30x30" %>
								<span class="font-bold" style="font-size: 20px;"><%= cart_item.item.name %></span>
							</td>
							<td class="txt-c ver-m">
								<span class="font-bold" style="font-size: 20px;"><%= (cart_item.item.price*1.1).round %></span>
							</td>
							<td class="txt-c ver-m">
								<%= form_for(cart_item) do |f| %>
									<%= f.number_field :amount, min: 1, max: 10 %>

									<%= f.submit('変更', class: 'btn btn-primary') %>
								<% end %>
							</td>
							<td class="txt-c ver-m">
								<span class="font-bold" style="font-size: 20px;"><%= ((cart_item.item.price*1.1).round)*(cart_item.amount) %></span>
							</td>
							<td class="txt-c ver-m">
								<%= link_to "削除する", cart_items_destroy_item_path(cart_item), method: :delete, class: "btn btn-danger" %>
							</td>
							
						</tr>

					<% end %>
				</tbody>
			</table>
		</div>
		<div class="row">
			<div class="col-xs-3">
				<%= link_to "買い物を続ける", items_path, class: "btn btn-primary col-xs-12" %>
			</div>
			<div class="col-xs-4 col-xs-offset-5">
				<table class="table table-bordered">
					<tbody>
						<tr>
							<td class="bgc-sil"><h4 class="font-bold">合計金額</h4></td>
							<td><h4 class="font-bold"><%= @total_price %></h4></td>
						</tr>
					</tbody>
				</table>				
			</div>
		</div>
	</div>
</div>
<div class="col-xs-4 col-xs-offset-4">
	<% if @total_price == 0 %>
		<%= link_to "情報入力に進む", items_path, class: "btn btn-success col-xs-12" %>
	<% else %>
		<%= link_to "情報入力に進む", new_order_path, class: "btn btn-success col-xs-12" %>
	<% end %>
</div>