config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  devise_for :end_users
  devise_for :admins

  namespace :admins do
    resources :end_users, only: [:index, :show, :edit, :update]
  	resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  get 'end_users/yours' => 'end_users#yours', as: 'end_user_yours'
  get 'end_users/yours/edit' => 'end_users#edit', as: 'end_user_edit'
  get 'end_users/leave' => 'end_users#leave', as: 'end_user_leave'
  patch 'end_users/:id/hide' => 'end_users#hide', as: 'end_user_hide'
  resources :end_users, only: [:update]
  
  resources :items, only: [:index, :show]
  
  delete 'cart_items/item/:id' => 'cart_items#destroy_item', as: 'cart_items_destroy_item'
  delete 'cart_items' => 'cart_items#destroy_cart', as: 'cart_items_destroy_cart'
  resources :cart_items, only: [:index, :create, :update]

  post 'orders/confirm' => 'orders#confirm', as: 'confirm_order'
  get 'orders/complete' => 'orders#complete', as: 'complete_order'
  resources :orders, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  acts_as_paranoid
end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController
  def index
  	@end_users = EndUser.with_deleted.all
  end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  def yours
    @end_user = current_end_user
  end

  def edit
    @end_user = current_end_user
  end

  def update
    @end_user = current_end_user
    if @end_user.update(end_user_params)
      redirect_to end_user_yours_path
    else
      render 'edit'
    end
  end

  def leave
    @end_user = current_end_user
  end

  def hide
    @end_user = current_end_user
    @end_user.destroy
    redirect_to new_end_user_session_path
  end

  private
  def end_user_params
    params.require(:end_user).permit(:last_name, :first_name,
      :kana_last_name, :kana_first_name, :email, :postal_code,
      :address, :phone_number)
    
  end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/end_users/edit.html.erb
<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-2">
    <div class="title-box">
      <h4>登録情報編集</h4>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10">

    <%= form_for(@end_user) do |f| %>
		<div class="row">
	        <div class="col-xs-2">
	          <p class="txt-l">名前</p>
	        </div>

	        <div class="col-xs-1">
	          <p class="txt-r">(姓)</p>
	        </div>
	        <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", :class => "col-xs-4" %>
	        
	        <div class="col-xs-1">
	          <p class="txt-r">(名)</p>
	        </div>
	        <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", :class => "col-xs-4" %>
	    </div>

	    <div class="row">
	        <div class="col-xs-2">
	          <p class="txt-l">フリガナ</p>
	        </div>

	        <div class="col-xs-1">
	          <p class="txt-r">(セイ)</p>
	        </div>
	        <%= f.text_field :kana_last_name, autofocus: true, autocomplete: "kana_last_name", :class => "col-xs-4" %>
	        
	        <div class="col-xs-1">
	          <p class="txt-r">(メイ)</p>
	        </div>
	        <%= f.text_field :kana_first_name, autofocus: true, autocomplete: "kana_first_name", :class => "col-xs-4" %>
	    </div>

	    <div class="row">
	        <div class="col-xs-3 txt-l">
	          <p>メールアドレス</p>
	        </div>
	        <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => 'col-xs-4' %>
	    </div>

	    <div class="row">
	        <div class="col-xs-3 txt-l">
	          <p>郵便番号(ハイフンなし)</p>
	        </div>
	        <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", :class => 'col-xs-4' %>
	    </div>

	    <div class="row">
	        <div class="col-xs-3 txt-l">
	          <p>住所</p>
	     	</div>
	        <%= f.text_field :address, autofocus: true, autocomplete: "address", :class => 'col-xs-9' %>
	    </div>

	    <div class="row">
	    	<div class="col-xs-3 txt-l">
	          <p>電話番号(ハイフンなし)</p>
	        </div>
	        <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number", :class => 'col-xs-4' %>
	    </div>

	    <div class="row">
	    	<div class="col-xs-9">
	    		<div class="actions row signup-btn signup-box">
		        	<%= f.submit "編集内容を保存する", :class => 'col-xs-4 btn btn-primary fl-none' %>
		        	
		    	</div>
		    </div>
		    <div class="col-xs-3">
		    	<div class="actions row signup-btn signup-box">
		        	<%= link_to "退会する", end_user_leave_path, class: "col-xs-8 btn btn-danger fl-none" %>
		        	
		    	</div>
		    </div>
		</div>

    <% end %>
  </div>
  <div class="col-xs-1"></div>
</div>

app/views/end_users/leave.html.erb
<div class="row">
	<div class="col-xs-3"></div>
	<div class="col-xs-6">
		<div class="row">
			<h3 class="txt-c leave-title font-bold">本当に退会しますか？</h>
		</div>
		<div class="row">
			<h4 class="txt-c">退会すると、会員登録情報や<br>
				これまでの購入履歴が閲覧できなくなります。<br>
				退会する場合は、「退会する」をクリックしてください。
			</h4>
		</div>
		<div class="row">
			<nav>
				<ul class="leave-nav">
		            <li class="leave-li">
		              <%= link_to "退会しない", end_user_yours_path, class: "btn btn-primary leave-btn" %>
		            </li>
		            <li class="leave-li">
		            	<%= link_to "退会する", end_user_hide_path(@end_user), method: :patch, data: {confirm: "本当に消しますか?"}, class: "btn btn-danger leave-btn" %>
		            </li>
				</ul>
			</nav>
		</div>
	</div>
	<div class="col-xs-3"></div>
</div>

app/views/end_users/yours.html.erb
<div class="row">
	<div class="col-xs-3 title-box" style="margin-left: 130px;">
		<h4>マイページ</h4>
	</div>
	<div class="col-xs-6"></div>
</div>

<div class="row">
	<nav>
		<ul class="yours-nav">
			<li class="yours-li">
              <h4 class="font-bold yours-li-txt">登録情報</h4>
            </li>

            <li class="yours-li">
              <%= link_to "編集する", end_user_edit_path, class: "btn btn-primary yours-btn" %>
            </li>
            <li class="yours-li">
            	<%= link_to "パスワードを変更する", new_end_user_registration_path, class: "btn btn-primary yours-btn" %>
            </li>
		</ul>
	</nav>
</div>

<div class="row">
	<div class="col-xs-9">
		<table class="table table-bordered">
			<tbody>
				<tr>
					<td class="font-bold bgc-sil">氏名</td>
					<td class="font-bold"><%= @end_user.last_name %> <%= @end_user.first_name %></td>
				</tr>
				<tr>
					<td class="font-bold bgc-sil">カナ</td>
					<td class="font-bold"><%= @end_user.kana_last_name %> <%= @end_user.kana_first_name %></td>
				</tr>
				<tr>
					<td class ="font-bold bgc-sil" >郵便番号</td>
					<td class="font-bold"><%= @end_user.postal_code %></td>
				</tr>
				<tr>
					<td class="font-bold bgc-sil bgc-sil" >住所</td>
					<td class="font-bold"><%= @end_user.address %></td>
				</tr>
				<tr>
					<td class="font-bold bgc-sil">電話番号</td>
					<td class="font-bold"><%= @end_user.phone_number %></td>
				</tr>
				<tr>
					<td class="font-bold bgc-sil" >メールアドレス</td>
					<td class="font-bold"><%= @end_user.email %></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<div class="row">
	<nav>
		<ul class="yours-nav">
			<li class="yours-li">
              <h4 class="font-bold yours-li-txt">配送先</h4>
            </li>

            <li class="yours-li">
              <%= link_to "一覧を見る", new_end_user_registration_path, class: "btn btn-primary yours-btn" %>
            </li>
		</ul>
	</nav>
</div>

<div class="row">
	<nav>
		<ul class="yours-nav">
			<li class="yours-li">
              <h4 class="font-bold yours-li-txt">注文履歴</h4>
            </li>

            <li class="yours-li">
              <%= link_to "一覧を見る", new_end_user_registration_path, class: "btn btn-primary yours-btn" %>
            </li>
		</ul>
	</nav>
</div>