config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  devise_for :end_users
  devise_for :admins

  namespace :admins do
    resources :end_users, only: [:index, :show, :edit, :update]
  	resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  get 'end_users/yours' => 'end_users#yours', as: 'end_user_yours'
  get 'end_users/yours/edit' => 'end_users#edit', as: 'end_user_edit'
  get 'end_users/leave' => 'end_users#leave', as: 'end_user_leave'
  patch 'end_users/:id/hide' => 'end_users#hide', as: 'end_user_hide'
  resources :end_users, only: [:update]
  
  resources :items, only: [:index, :show]
  
  delete 'cart_items/item/:id' => 'cart_items#destroy_item', as: 'cart_items_destroy_item'
  delete 'cart_items' => 'cart_items#destroy_cart', as: 'cart_items_destroy_cart'
  resources :cart_items, only: [:index, :create, :update]

  post 'orders/confirm' => 'orders#confirm', as: 'confirm_order'
  get 'orders/complete' => 'orders#complete', as: 'complete_order'
  resources :orders, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/addresse.rb
class Addresse < ApplicationRecord

	belongs_to :end_user


	def address_information
		self.postal_code + " " + self.address + " " + self.name
	end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

	belongs_to :end_user
	belongs_to :item

end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  acts_as_paranoid
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre
	attachment :image

	has_many :cart_items, dependent: :destroy
	has_many :order_details , dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :end_user
	has_many :order_details, dependent: :destroy

	enum payment_method: {  credit_card: 0, 
							bank: 1
						}
	enum order_status: {  	wait_payment: 0,
	 						confirm_payment: 1,
	 						now_making: 2,
	 						prepare_shipment: 3,
	 						done_shipment: 4
	 					}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

	belongs_to :item
	belongs_to :order

	enum make_status: { cannot_start: 0,
						wait_making: 1,
						now_making: 2,
						complete_making: 3
					}
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
  end

  def edit
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart_items = CartItem.all
    @total_price = 0
    @cart_items.each do |cart_item|
      @total_price = @total_price + ((cart_item.item.price*1.1).round)*cart_item.amount 
    end
  end

  def create
    @cart_item = current_end_user.cart_items.new(cart_item_params)
    if presence = current_end_user.cart_items.find_by(item_id: params[:cart_item][:item_id]) 
      amount = @cart_item.amount + presence.amount
      presence.update(amount: amount)
      redirect_to cart_items_path
    else
      @cart_item.save
      redirect_to cart_items_path
    end
  end

  def update
  	@cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy_item
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_cart
    @end_user = current_end_user
    EndUser.find(@end_user.id).cart_items.destroy_all
    redirect_to items_path
  end

  private
  def cart_item_params
  	params.require(:cart_item).permit(:amount, :end_user_id, :item_id)
  end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  def yours
    @end_user = current_end_user
  end

  def edit
    @end_user = current_end_user
  end

  def update
    @end_user = current_end_user
    if @end_user.update(end_user_params)
      redirect_to end_user_yours_path
    else
      render 'edit'
    end
  end

  def leave
    @end_user = current_end_user
  end

  def hide
    @end_user = current_end_user
    @end_user.destroy
    redirect_to new_end_user_session_path
  end

  private
  def end_user_params
    params.require(:end_user).permit(:last_name, :first_name,
      :kana_last_name, :kana_first_name, :email, :postal_code,
      :address, :phone_number)
    
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

def index
	@end_user = current_end_user
	@items = Item.all
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  before_action :confirm_cart_item, only: [:new, :confirm, :create]

  def new
    @order = Order.new
  end

  def confirm
    if order_params[:payment_method] == nil || order_params[:select_address] == nil
      redirect_to new_order_path
    end

    session[:payment_method] = order_params[:payment_method]
    @select_address = order_params[:select_address]
    
    if order_params[:select_address] == "3"
      session[:ship_postal_code] = order_params[:ship_postal_code]
      session[:ship_address] = order_params[:ship_address]
      session[:ship_name] = order_params[:ship_name]
    
    elsif order_params[:select_address] == "2"
      @address = Addresse.find_by(id: order_params[:address_info])
    end

    @order = Order.new
    @cart_items = CartItem.all
    @total_price = 0
    @cart_items.each do |cart_item|
      @total_price = @total_price + ((cart_item.item.price*1.1).round)*cart_item.amount
    end


  end

  def create
    @order = Order.new
    if order_params[:select_address] == "1"
      @order.ship_name = current_end_user.last_name + current_end_user.first_name
      @order.ship_address = current_end_user.address
      @order.ship_postal_code = current_end_user.postal_code
    
    elsif order_params[:select_address] == "2"
      @address = Addresse.find_by(id: order_params[:address_info])
      @order.ship_name = @address.name
      @order.ship_address = @address.address
      @order.ship_postal_code = @address.postal_code

    else
      @order.ship_name = order_params[:ship_name]
      @order.ship_address = order_params[:ship_address]
      @order.ship_postal_code = order_params[:ship_postal_code]
    
    end
    
    @order.end_user_id = current_end_user.id
    @order.payment = order_params[:payment]
    @order.postage = 800
    @order.payment_method = (order_params[:payment_method]).to_i
    @order.save

    current_end_user.cart_items.each do |cart_item|
      order_detail = OrderDetail.new
      order_detail.item_id = cart_item.item.id
      order_detail.order_id = @order.id
      order_detail.amount = cart_item.amount
      order_detail.buy_price = cart_item.item.price
      order_detail.save
    end
    CartItem.destroy_all

    redirect_to complete_order_path

  end

  def complete
    #画面表示のみ
  end

  def confirm_cart_item
  	@cart_items = CartItem.all
    @total_price = 0
    @cart_items.each do |cart_item|
      @total_price = @total_price + ((cart_item.item.price*1.1).round)*cart_item.amount
    end

    if @total_price == 0
    	redirect_to items_path
    end
  end


  private

  def order_params
    params.require(:order).permit(:payment, :payment_method, :ship_name, :ship_address, 
                                    :ship_postal_code, :select_address, :address_info)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YazawaCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container-fluid clearfix under-line">
        <div class="box-logo">
          <h2>Nagano Cake</h2>
        </div>

        <nav>
          <ul class="nav">

            <% if admin_signed_in? %>
              <li class="nav-list">
              <%= link_to "商品一覧", admins_items_path, class: "btn btn-default nav-btn" %>
            </li>

            <li class="nav-list">
              <%= link_to "会員一覧", new_admins_item_path, class: "btn btn-default nav-btn" %>
            </li>

            <li class="nav-list">
              <%= link_to "注文履歴一覧", admins_orders_path, class: "btn btn-default nav-btn" %>
            </li>


            <li class="nav-list">
              <%= link_to "ジャンル管理", admins_genres_path, class: "btn btn-default nav-btn" %>
            </li>

            <div class="row">
              <div class="col-xs-4 col-xs-offset-8">
                <%= form_tag(admins_items_path,:method => 'get') do %>
                  <%= text_field_tag :search %>
                  <%= submit_tag 'Search', :name => nil %>
                <% end %>
              </div>
            </div>


          <% elsif end_user_signed_in? %>
          <li class="nav-list nav-list-login li-text">
            ようこそ、<span><%= current_end_user.last_name %></span>さん！
          </li>

          <li class="nav-list nav-list-login">
              <%= link_to "マイページ", end_user_yours_path, class: "btn btn-default nav-btn" %>
            </li>

             <li class="nav-list nav-list-login">
              <%= link_to "商品一覧", items_path, class: "btn btn-default nav-btn" %>
            </li>

            <li class="nav-list nav-list-login">
              <%= link_to "カート", cart_items_path, class: "btn btn-default nav-btn" %>
            </li>   

            <li class="nav-list nav-list-login">
              <%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class: "btn btn-default nav-btn" %>
            </li>   
            
          <% else %>
            
            <li class="nav-list nav-list">
              <%= link_to "商品一覧", items_path, class: "btn btn-default nav-btn" %>
            </li>  

            <li class="nav-list">
              <%= link_to "新規登録", new_end_user_registration_path, class: "btn btn-default nav-btn" %>
            </li>

            <li class="nav-list">
              <%= link_to "ログイン", new_end_user_session_path, class: "btn btn-default nav-btn" %>
            </li>
 
          <% end %>
          </ul>
        </nav>

        
            
      </div>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>